#define CPU_eax 16 /* __builtin_offsetof(struct cpu_state, eax) */
#define CPU_ebx 20 /* __builtin_offsetof(struct cpu_state, ebx) */
#define CPU_ecx 24 /* __builtin_offsetof(struct cpu_state, ecx) */
#define CPU_edx 28 /* __builtin_offsetof(struct cpu_state, edx) */
#define CPU_esi 32 /* __builtin_offsetof(struct cpu_state, esi) */
#define CPU_edi 36 /* __builtin_offsetof(struct cpu_state, edi) */
#define CPU_ebp 40 /* __builtin_offsetof(struct cpu_state, ebp) */
#define CPU_esp 44 /* __builtin_offsetof(struct cpu_state, esp) */
#define CPU_ax 16 /* __builtin_offsetof(struct cpu_state, ax) */
#define CPU_bx 20 /* __builtin_offsetof(struct cpu_state, bx) */
#define CPU_cx 24 /* __builtin_offsetof(struct cpu_state, cx) */
#define CPU_dx 28 /* __builtin_offsetof(struct cpu_state, dx) */
#define CPU_si 32 /* __builtin_offsetof(struct cpu_state, si) */
#define CPU_di 36 /* __builtin_offsetof(struct cpu_state, di) */
#define CPU_bp 40 /* __builtin_offsetof(struct cpu_state, bp) */
#define CPU_sp 44 /* __builtin_offsetof(struct cpu_state, sp) */
#define CPU_eip 176 /* __builtin_offsetof(struct cpu_state, eip) */
#define CPU_gs 344 /* __builtin_offsetof(struct cpu_state, gs) */
#define CPU_tls_ptr 348 /* __builtin_offsetof(struct cpu_state, tls_ptr) */
#define CPU_eflags 180 /* __builtin_offsetof(struct cpu_state, eflags) */
#define CPU_of 189 /* __builtin_offsetof(struct cpu_state, of) */
#define CPU_cf 188 /* __builtin_offsetof(struct cpu_state, cf) */
#define CPU_res 192 /* __builtin_offsetof(struct cpu_state, res) */
#define CPU_op1 196 /* __builtin_offsetof(struct cpu_state, op1) */
#define CPU_op2 200 /* __builtin_offsetof(struct cpu_state, op2) */
#define CPU_flags_res 204 /* __builtin_offsetof(struct cpu_state, flags_res) */
#define CPU_df_offset 184 /* __builtin_offsetof(struct cpu_state, df_offset) */
#define CPU_fsw 336 /* __builtin_offsetof(struct cpu_state, fsw) */
#define CPU_xmm 48 /* __builtin_offsetof(struct cpu_state, xmm) */
#define PF_RES 1 /* (1 << 0) */
#define ZF_RES 2 /* (1 << 1) */
#define SF_RES 4 /* (1 << 2) */
#define AF_OPS 8 /* (1 << 3) */
#define PF_FLAG 4 /* (1 << 2) */
#define AF_FLAG 16 /* (1 << 4) */
#define ZF_FLAG 64 /* (1 << 6) */
#define SF_FLAG 128 /* (1 << 7) */
#define DF_FLAG 1024 /* (1 << 10) */
#define LOCAL_bp 360 /* __builtin_offsetof(struct jit_frame, bp) */
#define LOCAL_value 376 /* __builtin_offsetof(struct jit_frame, value) */
#define LOCAL_value_addr 368 /* __builtin_offsetof(struct jit_frame, value_addr) */
#define LOCAL_last_block 392 /* __builtin_offsetof(struct jit_frame, last_block) */
#define LOCAL_ret_cache 400 /* __builtin_offsetof(struct jit_frame, ret_cache) */
#define CPU_segfault_addr 352 /* __builtin_offsetof(struct cpu_state, segfault_addr) */
#define MEM_READ 0 /* 0 */
#define MEM_WRITE 1 /* 1 */
#define JIT_BLOCK_code 184 /* __builtin_offsetof(struct jit_block, code) */
#define TLB_entries 16 /* __builtin_offsetof(struct tlb, entries) */
#define TLB_dirty_page 8 /* __builtin_offsetof(struct tlb, dirty_page) */
#define TLB_ENTRY_page 0 /* __builtin_offsetof(struct tlb_entry, page) */
#define TLB_ENTRY_page_if_writable 4 /* __builtin_offsetof(struct tlb_entry, page_if_writable) */
#define TLB_ENTRY_data_minus_addr 8 /* __builtin_offsetof(struct tlb_entry, data_minus_addr) */
